//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewLocalizationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewLocalizationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ViewLocalizationResources", typeof(ViewLocalizationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a car.
        /// </summary>
        public static string Add_a_Car {
            get {
                return ResourceManager.GetString("Add_a_Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a driver.
        /// </summary>
        public static string Add_a_driver {
            get {
                return ResourceManager.GetString("Add_a_driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6) Add a car.
        /// </summary>
        public static string Add_Car {
            get {
                return ResourceManager.GetString("Add_Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add new car:.
        /// </summary>
        public static string Add_Car_Failed {
            get {
                return ResourceManager.GetString("Add_Car_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added new car succesfully..
        /// </summary>
        public static string Add_Car_Succes {
            get {
                return ResourceManager.GetString("Add_Car_Succes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5) Add a driver.
        /// </summary>
        public static string Add_Driver {
            get {
                return ResourceManager.GetString("Add_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add new driver:.
        /// </summary>
        public static string Add_Driver_Failed {
            get {
                return ResourceManager.GetString("Add_Driver_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added new driver succesfully..
        /// </summary>
        public static string Add_Driver_Succes {
            get {
                return ResourceManager.GetString("Add_Driver_Succes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7) Add a driver to car.
        /// </summary>
        public static string Add_Driver_To_Car {
            get {
                return ResourceManager.GetString("Add_Driver_To_Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new rental.
        /// </summary>
        public static string Add_Rental {
            get {
                return ResourceManager.GetString("Add_Rental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose garage:.
        /// </summary>
        public static string AddCar_Choose_garage {
            get {
                return ResourceManager.GetString("AddCar_Choose_garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All cars.
        /// </summary>
        public static string All_Cars {
            get {
                return ResourceManager.GetString("All_Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All drivers.
        /// </summary>
        public static string All_Drivers {
            get {
                return ResourceManager.GetString("All_Drivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4) All drivers with name and/or date of birth.
        /// </summary>
        public static string All_Drivers_Filtered {
            get {
                return ResourceManager.GetString("All_Drivers_Filtered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of miles on count:.
        /// </summary>
        public static string Amount_of_miles_on_count_ {
            get {
                return ResourceManager.GetString("Amount_of_miles_on_count_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of seats:.
        /// </summary>
        public static string Amount_Of_Seats {
            get {
                return ResourceManager.GetString("Amount_Of_Seats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to born on {0}.
        /// </summary>
        public static string Born_On_Date {
            get {
                return ResourceManager.GetString("Born_On_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Insurance.
        /// </summary>
        public static string Car_Insurance {
            get {
                return ResourceManager.GetString("Car_Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice (0, 9): .
        /// </summary>
        public static string Choice {
            get {
                return ResourceManager.GetString("Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s not a valid culture, please try again..
        /// </summary>
        public static string Culture_Invalid {
            get {
                return ResourceManager.GetString("Culture_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth (mm/dd/yyyy): .
        /// </summary>
        public static string Date_Of_Birth {
            get {
                return ResourceManager.GetString("Date_Of_Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This driver does not exist. Please try again..
        /// </summary>
        public static string Driver_Not_Exist {
            get {
                return ResourceManager.GetString("Driver_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string en_US {
            get {
                return ResourceManager.GetString("en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a full date (yyyy/mm/dd) or leave blank: .
        /// </summary>
        public static string Enter_a_full_date__yyyy_mm_dd__or_leave_blank__ {
            get {
                return ResourceManager.GetString("Enter_a_full_date__yyyy_mm_dd__or_leave_blank__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an car ID: .
        /// </summary>
        public static string Enter_Car_ID {
            get {
                return ResourceManager.GetString("Enter_Car_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter (part of) a name or leave blank:.
        /// </summary>
        public static string Enter_part_of_a_name_or_leave_blank_ {
            get {
                return ResourceManager.GetString("Enter_part_of_a_name_or_leave_blank_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye.
        /// </summary>
        public static string Exit_Message {
            get {
                return ResourceManager.GetString("Exit_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, please try again..
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firstname: .
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string fr_FR {
            get {
                return ResourceManager.GetString("fr-FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        public static string Fuel {
            get {
                return ResourceManager.GetString("Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage.
        /// </summary>
        public static string Garage {
            get {
                return ResourceManager.GetString("Garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car with numberplate: {0} from {1} - on {2} {3}.
        /// </summary>
        public static string GetInfo_Car {
            get {
                return ResourceManager.GetString("GetInfo_Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much does the rental cost: .
        /// </summary>
        public static string How_much_does_the_rental_cost {
            get {
                return ResourceManager.GetString("How_much_does_the_rental_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lastname: .
        /// </summary>
        public static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Managed by garage &apos;{0}&apos;].
        /// </summary>
        public static string Managed_By_Garage {
            get {
                return ResourceManager.GetString("Managed_By_Garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string nl_BE {
            get {
                return ResourceManager.GetString("nl-BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not a valid option..
        /// </summary>
        public static string Not_A_Valid_Option {
            get {
                return ResourceManager.GetString("Not_A_Valid_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to optional.
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a driver ID: .
        /// </summary>
        public static string Please_enter_a_driver_ID {
            get {
                return ResourceManager.GetString("Please_enter_a_driver_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible cultures:.
        /// </summary>
        public static string Possible_Cultures {
            get {
                return ResourceManager.GetString("Possible_Cultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase price.
        /// </summary>
        public static string PurchasePrice {
            get {
                return ResourceManager.GetString("PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0) Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8) Remove driver from car.
        /// </summary>
        public static string Remove_Driver_From_Car {
            get {
                return ResourceManager.GetString("Remove_Driver_From_Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a rental.
        /// </summary>
        public static string Remove_Rental {
            get {
                return ResourceManager.GetString("Remove_Rental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which car would you like to remove a driver from?.
        /// </summary>
        public static string Select_Car_Drive_Removal {
            get {
                return ResourceManager.GetString("Select_Car_Drive_Removal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a culture: .
        /// </summary>
        public static string Select_Culture {
            get {
                return ResourceManager.GetString("Select_Culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which driver would you like to remove from this car?.
        /// </summary>
        public static string Select_Driver_Car_Removal {
            get {
                return ResourceManager.GetString("Select_Driver_Car_Removal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Show all cars.
        /// </summary>
        public static string Show_All_Cars {
            get {
                return ResourceManager.GetString("Show_All_Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3) Show all drivers.
        /// </summary>
        public static string Show_All_Drivers {
            get {
                return ResourceManager.GetString("Show_All_Drivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) Show cars by Fuel.
        /// </summary>
        public static string Show_Cars_By_Fuel {
            get {
                return ResourceManager.GetString("Show_Cars_By_Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9) Switch culture.
        /// </summary>
        public static string Switch_Culture {
            get {
                return ResourceManager.GetString("Switch_Culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated culture to .
        /// </summary>
        public static string Updated_Culture {
            get {
                return ResourceManager.GetString("Updated_Culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to do?.
        /// </summary>
        public static string What_would_you_like_to_do {
            get {
                return ResourceManager.GetString("What_would_you_like_to_do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which car would you like to add a driver to?.
        /// </summary>
        public static string Which_car_would_you_like_to_add_a_driver_to_ {
            get {
                return ResourceManager.GetString("Which_car_would_you_like_to_add_a_driver_to_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which driver would you like to add to this car?.
        /// </summary>
        public static string Which_driver_would_you_like_to_add_to_this_car {
            get {
                return ResourceManager.GetString("Which_driver_would_you_like_to_add_to_this_car", resourceCulture);
            }
        }
    }
}
