//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewLocalizationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewLocalizationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ViewLocalizationResources", typeof(ViewLocalizationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6) Add a car.
        /// </summary>
        public static string Add_Car {
            get {
                return ResourceManager.GetString("Add_Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5) Add a driver.
        /// </summary>
        public static string Add_Driver {
            get {
                return ResourceManager.GetString("Add_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7) Add a driver to car.
        /// </summary>
        public static string Add_Driver_To_Car {
            get {
                return ResourceManager.GetString("Add_Driver_To_Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4) All drivers with name and/or date of birth.
        /// </summary>
        public static string All_Drivers_Filtered {
            get {
                return ResourceManager.GetString("All_Drivers_Filtered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Insurance.
        /// </summary>
        public static string Car_Insurance {
            get {
                return ResourceManager.GetString("Car_Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice (0, 9): .
        /// </summary>
        public static string Choice {
            get {
                return ResourceManager.GetString("Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string en_US {
            get {
                return ResourceManager.GetString("en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye.
        /// </summary>
        public static string Exit_Message {
            get {
                return ResourceManager.GetString("Exit_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string fr_FR {
            get {
                return ResourceManager.GetString("fr-FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string nl_BE {
            get {
                return ResourceManager.GetString("nl-BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not a valid option..
        /// </summary>
        public static string Not_A_Valid_Option {
            get {
                return ResourceManager.GetString("Not_A_Valid_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible cultures:.
        /// </summary>
        public static string Possible_Cultures {
            get {
                return ResourceManager.GetString("Possible_Cultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0) Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8) Remove driver from car.
        /// </summary>
        public static string Remove_Driver_From_Car {
            get {
                return ResourceManager.GetString("Remove_Driver_From_Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Show all cars.
        /// </summary>
        public static string Show_All_Cars {
            get {
                return ResourceManager.GetString("Show_All_Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3) Show all drivers.
        /// </summary>
        public static string Show_All_Drivers {
            get {
                return ResourceManager.GetString("Show_All_Drivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) Show cars by Fuel.
        /// </summary>
        public static string Show_Cars_By_Fuel {
            get {
                return ResourceManager.GetString("Show_Cars_By_Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9) Switch culture.
        /// </summary>
        public static string Switch_Culture {
            get {
                return ResourceManager.GetString("Switch_Culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to do?.
        /// </summary>
        public static string What_would_you_like_to_do {
            get {
                return ResourceManager.GetString("What_would_you_like_to_do", resourceCulture);
            }
        }
    }
}
